### ISSUE TITLE
How to customize optimization methods

### ISSUE THREAD

**Issue by Zcaic** [relf/egobox#143]
Hello，I'm using egobox with python. I want to know if I can customize the optimization method.
I know egor optimizes with slsqp or cobyla, Is it possible to use the optimization algorithm provided by yourself in python? For example, I want to use differential evolution (DE) .

**Comment by relf** [comment]
Hi. The short answer is this is not possible. `Egor` is written in Rust and uses internally `Cobyla` (default) or `Slsqp` also written in Rust. If you develop in Rust we could imagine adding another kind of optimizer but adding a Python optimizer would be difficult (not to say a bit clumsy).

**Comment by Zcaic** [comment]
Thank you very much for your answer, I used smt before but I found egobox to be even better, especially in terms of speed and handling constraints!
