### ISSUE TITLE
Unable to save and load trained Gpx models in Python

### ISSUE THREAD

**Issue by relf** [relf/egobox#195]
The user @esnguyenvan 😉 wants to save and reload a trained `Gpx` model from Python.
Currently, the save/load feature is not available at the Python level, though implemented at the Rust level.

**Comment by relf** [comment]
Actually `save` and `load` are implemented in the `Gpx` python binding! 😃 See the [tutorial](https://github.com/relf/egobox/blob/master/doc/Gpx_Tutorial.ipynb) Example 2 section (the save/load methods are just not wrapped in smt `GPX` class wrapping... but it can be easily patched with something like:

```python
smt_gpx = GPX(...)

# save
smt_gpx._gpx.save("my_gpx.json")

# reload
smt_gpx._gpx.load("my_gpx.json")
```

**Comment by esnguyenvan** [comment]
Hey! Thanks for the tip! I was able to save correctly but had a bug when trying to load:

>self.wing_mass_L1._gpx.load(self.PATH_WING_L1.as_posix())
>AttributeError: 'NoneType' object has no attribute 'load'

It seems that when I instantiate a GPX the variable _gpx is None until train() is called. The following works but it's not very nice. What did I miss?

    self.wing_mass_L1.set_training_values(np.array([1.0,2.0,3.0]),np.array([1.0,2.0,3.0]))
    self.wing_mass_L1.train()
    self.wing_mass_L1._gpx.load(self.PATH_WING_L1.as_posix())`

**Comment by esnguyenvan** [comment]
Actually, the previous code runs but the GPX is not affected when running `.load()`, any idea of what is happening?

**Comment by relf** [comment]
Yes, my bad! The right loading code is:

```python
import egobox as egx 

# reload
smt_gpx = egx.Gpx.load("my_gpx.json")
```

**Comment by esnguyenvan** [comment]
Implemented and it works! Thanks!
Although the calls to the predict function are a bit different between SMT and egobox:

>`gpx.predict()` in egobox
>`gpx.predict_values()` in SMT

So I will probably switch to egobox only instead of SMT for GPX

**Comment by relf** [comment]
FYI, following https://github.com/SMTorg/smt/pull/658, using the current master of `smt`, you can save/load `GPX` models.
