### ISSUE TITLE
JOSS Review - Lorenz

### ISSUE THREAD

**Issue by bytesnake** [relf/egobox#41]
Everything looking fine

- [x] runners in place: linting + testing
- [x] tests + examples are working as expected
- [x] pointwise comparison to reference implementation in tests
- [x] crates items are fully documented
- [x] bindings to python interface

### Two small things

- you can include your readme for crates with https://blog.guillaume-gomez.fr/articles/2021-08-03+Improvements+for+%23%5Bdoc%5D+attributes+in+Rust
- https://docs.rs/egobox-ego/latest/src/egobox_ego/lib.rs.html#38

**Comment by relf** [comment]
Thanks for your review. I've taken into account your points in the [last commits of the joss branch](https://github.com/relf/egobox/compare/master...joss).
